using SmartOpsHub.Core.Models;

namespace SmartOpsHub.Core.Tests.Models;

public class ChatMessageTests
{
    [Fact]
    public void ChatMessage_GetsAutoGeneratedId()
    {
        var message = new ChatMessage { Role = ChatRole.User, Content = "Hello" };

        Assert.False(string.IsNullOrEmpty(message.Id));
    }

    [Fact]
    public void ChatMessage_GetsAutoGeneratedTimestamp()
    {
        var before = DateTimeOffset.UtcNow;
        var message = new ChatMessage { Role = ChatRole.User, Content = "Hello" };
        var after = DateTimeOffset.UtcNow;

        Assert.InRange(message.Timestamp, before, after);
    }

    [Fact]
    public void DifferentChatMessages_GetDifferentIds()
    {
        var message1 = new ChatMessage { Role = ChatRole.User, Content = "Hello" };
        var message2 = new ChatMessage { Role = ChatRole.Assistant, Content = "Hi" };

        Assert.NotEqual(message1.Id, message2.Id);
    }
}
